[package]
name = "default-net"
version = "0.10.0"
authors = ["shellrow <shellrow@protonmail.com>"]
edition = "2021"
description = "Cross-platform library for network interface and gateway"
repository = "https://github.com/shellrow/default-net"
readme = "README.md"
keywords = ["network"]
categories = ["network-programming"]
license = "MIT"

[target.'cfg(not(windows))'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies.windows]
version = "0.29.0"
features = ["Win32_Foundation","Win32_NetworkManagement_IpHelper"]

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
system-configuration = "0.5.0"
