[package]
name = "default-net"
version = "0.5.0"
authors = ["shellrow <81893184+shellrow@users.noreply.github.com>"]
edition = "2018"
description = "Get default network information"
repository = "https://github.com/shellrow/default-net"
readme = "README.md"
keywords = ["network"]
categories = ["network-programming"]
license = "MIT"

[dependencies]
pnet_packet = "0.28"
pnet_datalink = "0.28"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = [ "std" ] }
[dependencies.windows]
version = "0.29.0"
features = ["Win32_Foundation","Win32_NetworkManagement_IpHelper"]
