[package]
name = "default-net"
version = "0.2.1"
authors = ["shellrow <81893184+shellrow@users.noreply.github.com>"]
edition = "2018"
description = "Get default network information"
repository = "https://github.com/shellrow/default-net"
readme = "README.md"
keywords = ["network"]
categories = ["network-programming"]
license = "MIT"

[dependencies]
pnet = "0.28"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = [ "std" ] }
