[package]
name = "default-net"
version = "0.2.0"
authors = ["shellrow <81893184+shellrow@users.noreply.github.com>"]
edition = "2018"
description = "Get default network information"
repository = "https://github.com/shellrow/default-net"
readme = "README.md"
keywords = ["network"]
categories = ["network-programming"]
license = "MIT"

[target.'cfg(not(windows))'.dependencies]
pnet = "0.27"

[target.'cfg(target_os = "windows")'.dependencies]
pnet = "0.26"
